In [3]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split

In [4]:
dir2save = '/home/cz/mds3/data-centric/datasets/'

In [5]:
name2save= os.path.join(dir2save, 'prepared/urinary')

In [6]:
os.makedirs(name2save, exist_ok=True)

In [7]:
def read_arf_file(arf_file_path):
    data = []
    with open(arf_file_path, 'r', encoding='utf-8') as file:
        for line in file:
            # Processar cada linha conforme necess√°rio
            # Aqui, apenas adicionando cada linha aos dados
            data.append(line.strip())
    return data

In [8]:
# Exemplo de uso
arf_data = read_arf_file(dir2save+"phpOAYun7.arff")

In [9]:
data = arf_data[121:]

In [10]:
attributes = arf_data[112:119]

In [11]:
columns_extracted = []

# Analise cada string na lista de atributos
for attribute in attributes:
    # Separe o nome do atributo e o tipo de dados
    parts = attribute.split()
    attribute_name = parts[1]
    data_type = parts[2]
    columns_extracted.append(attribute_name)

In [12]:
new_data = []
for i in range(len(data)):
    new_data.append(data[i].split(','))

In [13]:
new_data = np.array(new_data)

In [14]:
new_datafloat = []
for obtained in new_data:
    new_obtained = []
    for info in obtained:
        try:
            new_obtained.append(float(info))
        except ValueError:
            if info=='no':
                new_obtained.append(1)
            else:
                new_obtained.append(0)
    new_datafloat.append(new_obtained)

In [15]:
new_datafloat = np.array(new_datafloat)

In [16]:
new_datafloat.shape

(120, 7)

In [17]:
new_datafloat

array([[35.5,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [35.9,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [35.9,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36. ,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36. ,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36.2,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.2,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36.3,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.6,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.6,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.6,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36.6,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36.7,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.7,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36.7,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [36.8,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.8,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.9,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [36.9,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37. ,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37. ,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37. ,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37. ,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.1,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.1,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37.1,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.2,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.2,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.2,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.3,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.3,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37.3,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.4,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.4,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.5,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.5,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.5,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.5,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37.5,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.5,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.6,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.6,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.6,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37.7,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.7,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.7,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.7,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.8,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.8,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37.8,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [37.9,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.9,  1. ,  1. ,  0. ,  0. ,  1. ,  1. ],
       [37.9,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ],
       [37.9,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ],
       [37.9,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ],
       [38. ,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [38. ,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [38.1,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [38.3,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [38.5,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [38.7,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [38.9,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [39. ,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [39.4,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [39.7,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [40. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [40. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [40. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [40. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [40. ,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [40. ,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [40. ,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [40.1,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [40.2,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [40.2,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [40.3,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [40.4,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [40.4,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40.4,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40.4,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [40.4,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [40.5,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [40.6,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [40.6,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [40.7,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [40.7,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40.7,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [40.7,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [40.7,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [40.8,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [40.9,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40.9,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [40.9,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [41. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [41. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [41. ,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [41. ,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [41.1,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [41.1,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [41.1,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [41.1,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [41.1,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [41.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [41.2,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [41.2,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [41.2,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [41.3,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [41.4,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [41.5,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [41.5,  0. ,  0. ,  1. ,  0. ,  1. ,  0. ],
       [41.5,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [41.5,  1. ,  0. ,  0. ,  1. ,  0. ,  0. ]])

In [18]:
df= pd.DataFrame(new_datafloat, columns = columns_extracted)

In [25]:
df = df.rename(columns={'V1': 'target'})

In [26]:
df

     target   V2   V3   V4   V5   V6  Class
0      35.5  1.0  0.0  1.0  1.0  1.0    1.0
1      35.9  1.0  1.0  0.0  0.0  0.0    1.0
2      35.9  1.0  0.0  1.0  1.0  1.0    1.0
3      36.0  1.0  1.0  0.0  0.0  0.0    1.0
4      36.0  1.0  0.0  1.0  1.0  1.0    1.0
..      ...  ...  ...  ...  ...  ...    ...
115    41.4  1.0  0.0  0.0  1.0  0.0    0.0
116    41.5  1.0  1.0  1.0  1.0  1.0    1.0
117    41.5  0.0  0.0  1.0  0.0  1.0    0.0
118    41.5  1.0  0.0  0.0  1.0  0.0    0.0
119    41.5  1.0  0.0  0.0  1.0  0.0    0.0

[120 rows x 7 columns]

In [27]:
df_train, df_test = train_test_split(df, test_size=0.33, random_state=42)

In [28]:
df_train.shape, df_test.shape

((80, 7), (40, 7))

In [29]:
df_train

     target   V2   V3   V4   V5   V6  Class
33     37.2  1.0  1.0  0.0  1.0  1.0    1.0
25     37.0  1.0  1.0  0.0  0.0  0.0    1.0
69     39.7  1.0  0.0  0.0  1.0  0.0    0.0
28     37.1  1.0  0.0  1.0  1.0  1.0    1.0
98     40.9  0.0  0.0  0.0  0.0  1.0    0.0
..      ...  ...  ...  ...  ...  ...    ...
106    41.1  0.0  0.0  0.0  0.0  1.0    0.0
14     36.7  1.0  0.0  1.0  1.0  1.0    1.0
92     40.7  0.0  0.0  0.0  0.0  0.0    0.0
51     37.7  1.0  1.0  0.0  1.0  1.0    1.0
102    41.0  1.0  1.0  1.0  1.0  1.0    1.0

[80 rows x 7 columns]

In [30]:
df_train.to_csv(os.path.join(name2save, 'urinary_train.csv'))

In [31]:
df_test.to_csv(os.path.join(name2save, 'urinary_test.csv'))